version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
      
  server:
    build: 
      context: 'server'
    container_name: server
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: items_db
    volumes:
      - items-db-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  items-db-data:
